### PR TITLE
setup flask app package, create qr code endpoint

### PR DESCRIPTION
**Pull request by mmc1718**
- createQR endpoing to take a url string, encode, generate qr code png image and return it as a png file
- unit test to check basic functionality

The qr code has been testing using a phone qr code scanner.

TODO:
- test content of qr code
- validate uuid endpoint

### CODE REVIEW

**Comment by VeraBrockmeyer** [comment]
Hello Mary,

do you like to run this in the seatable cloud or as backend separate?
If yes:
Unfortunately, I also tried it with a multi module approach but this is not working in the seatable cloud.
It needs to be all in one file. :( This is why I created and updated the DummyScript which has the basis and just need to be extended with the actual task logic.
else: 
 I would agree to the merge

**Comment by mmc1718** [comment]
Hey :)

I was planning this to be a separate backend service which seatable could
send requests to.
For the next steps and accessing seatable from a separate flask backend I
understand there is an API that can be called externally using a token?
At some point if you do have time to meet to talk through seatable and the
workflow I would appreciate it :)

**Comment by VeraBrockmeyer** [comment]
Hey, 
yes this token thing is a bit tricky. 

We can have a call now or on Tuesday. Or you checkout the DummyScript for an example and especially the DebugMode. This is a mode I introduced for convenience. Anyway, I'm a C/C++ developer. Thus please forgive me, if I dont solve in the best python way. 

Right now, I'm also writting a Getting Started for more information. Give me 20min and I will upload it.

**Comment by mmc1718** [comment]
Ok great, I will check out the DummyScript. Tuesday works for me for a call, I have filled in the survey Marcus sent me so you should have got my responses :)

**Comment by VeraBrockmeyer** [comment]
Yeah, we scheduled now for 1900-2000. But I think you dont need the full tour as python developer and we can have a shorter call around 18300. If this is okay?

**Comment by mmc1718** [comment]
1830 works great, thanks. You can send me the zoom link, I think you have my email but just in case marymcguire1718@gmail.com

**Pull request merged**
